[package]
name = "osrssg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"
bevy_picking = { version = "0.16.1", features = ["bevy_mesh_picking_backend"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
